lideres <- c("azucenau", "lopezdoriga", "chumeltorres", "V_TrujilloM", "FedericoArreola",
             "AristeguiOnline", "rivapa", "JoseCardenas1", "brozoxmiswebs", "DeniseDresserG",
             "VILLALVAZO13", "SergioSarmiento", "beltrandelrio", "jenarovillamil", "hdemauleon",
             "alvaro_delgado", "jairocalixto", "EnriqueKrauze", "genarolozano", "PedroFerriz",
             "carolina_rocha_", "epigmenioibarra", "PaolaRojas", "JohnMAckerman", "callodehacha",
             "karlaiberia", "lydiacachosi", "leozuckermann", "CiroGomezL", "mariocampos",
             "warkentin", "ruizhealy", "sanjuananotimex", "jrisco", "Adela_Micha",
             "PabloHiriart", "DeniseMaerker", "julioastillero", "YuririaSierra", "AnaPOrdorica",
             "juliopatan09", "SGarciaSoto", "macariomx", "RicardoAlemanMx", "AlvaroCueva",
             "MarioBeteta", "puigcarlos", "franciscozea", "kdartigues", "JavierSolorzano",
             "letroblesrosa", "mario_dico50", "Miriam_Junne", "vampipe", "rochaperiodista",
             "GlodeJo07", "jorgeberry", "DavidPramo2", "avieu", "AngelVerdugoB",
             "LupitaJuarezH", "HanniaNovell", "LuisCardenasMx", "burrovan", "LuisGyG",
             "manuelanorve", "BlancaBecerril", "NachoRgz", "aracelibs", "lumendoz",
             "jenarovillamil", "PelonGomis", "ferbelaunzaran", "EGaona14", "JJDiazMachuca",
             "Arouet_V", "SoyNinoCanun", "calbert57", "julian181407", "kompi1570",
             "marcial_diaz", "cocodiaze", "lolitavargas11", "LicEncarna", "Jnner", "_VicenteSerrano",
             "stumped77", "HombreTiro", "BstrdLucky", "SalatielDL", "happygu82717539",
             "cecyboney", "TaliaChelin", "il_moncho", "Pulbius", "BAMBUINM",
             "oax_libre2016", "EstefaniaVeloz", "eilumina2", "javodelocho", "2018CAMBIOREAL",
             "cuicardozo", "tribipiolin0t", "pulques_elrey", "OiseauAguilera", "EliActivista",
             "Itandehui_RoMa", "RomanoXIV", "alomen1", "octavioocs", "TapiaOlimpia",
             "ttriunvirat", "Matapzu", "Espacio108", "Antoni9542", "hgromeros76",
             "l2udo", "tochtliiztac", "rogeliotapiar", "Jimeno58913946", "fceg4",
             "dragondelanoche", "LupitaJuarezH", "estoyanovich", "jorgecantonz", "Alex_Menaf",
             "PedroAnton30", "noemarca_", "cinemusicmexico", "pipobolo", "ELPINERO",
             "acantonmx", "la300_is", "progresason", "abogadhillo", "Pelonndenfrente",
             "Gajon_C", "5antaMerlina", "juan3pueblo", "preciso_com", "laurivme",
             "Hilario75128383","PlacidoGarza", "AnaPaulaSan18", "jimmyfaro", "FernandezHumm",
             "adiazpi", "Jorge_MoralesB", "periodistafrg", "dayan_shalom", "EdAraMon2",
             "alasuroboro", "gerardjarteaga", "SHeyserBeltran", "AVidrio5", "estrella_gus",
             "mvs2709", "GonaLaca", "delfinazul119", "alvarezguillerm", "grumais",
             "IrvingGatell", "bereaguilarv", "MrLotario", "lordmolecula", "Pamelita0321",
             "FarukMTake", "adrifadi", "diamondbullok", "ness5791", "Itta76728784",
             "Fidel_el_de_aca", "BotTita2", "PLakech", "fragajraul", "ingeelectronico", 
             "JuanEspinosaV", "Carmen_MtzQ", "urgecambiaramex", "ManuelVegaMX", "a_zamorag",
             "MorenaMia25", "memoriasdf", "ElsyObradorova", "benitoparra", "marcocancinoavi",
             "_CarlosRN_", "Lobo_IFA", "chavomorales2", "yukaile", "JerryLD1",
             "Tony_RojMx", "Cabelloslacios", "VictorAnayaMen1", "adrianojedacast", "SheepOnTheSpace",
             "carlosmanuelgro", "JoseLuisMunguia", "CrMageva", "aldemok", "Silvia56883750",
             "AdrianaRendonM", "Gualujima", "gilortegavaldes", "cazador1954", "PipopeCifuentes",
             "Flavio6107ROCA", "CharlieMelano63", "MBustillosMX", "JavierJmnz4",
             "dnrofi", "danocamx", "lawyerestrada1", "Manolodeflorida", "2Azcarate",
             "pacocalderon", "araj_zaid", "sandia19334752", "LUISG36110177", "chismeador",
             "penmargo", "Santos8Roxanna", "VicClot", "MglMauricio",
             "JLozanoA", "ManuelCardenasE", "LunaEva7", "yoriman", "Javier_Alatorre",
             "Euge1564", "catrina_nortena", "Luz213And0", "QuesaVerdadess", "galvanochoa",
             "NEUROSURGEONNN", "terelagos", "liebano",  "nonalorehedzg03", "HernanGomezB",
             "blancasmadrigal", "AlbertoEsteva", "IrmaMR3", "VicenteFoxQue",
             "MennyValdz", "RiosCorona222", "BicireporteraDF", "elhijodelrayo", "rcavada",
             "Alejandro_Lelo", "salvadorcosio1","ChrisMurphyCT", "syzavel19", "fernandeznorona",
             "RoanaBuenavent1", "Mike_Oviedo", "DonPorfifirio", "luisestrada_", "LauraUlloa_CUN", 
             "ChicShion", "AleB1808", "gibranrr", "kenialopezr", "JTrianaT",
             "ClouthierManuel", "OpinadorTuitero", "HectorAtarrabia", "TheBigLudwig", "rubengluengas",
             "jgnaredo", "Navegaciones", "LauraBruges", "elisaalanis", "jiots",
             "RAFAELCORTES1", "YosoyPedrero", "MissSunshine4",  "luisghernan", "anafvega", 
             "BrunoCortesFP", "allizesalgado", "macamposr52", "nayeli786", "CarlosLoret",
             "TapiaFernanda", "NormanFPearl", "ElverGonzoso8", "La_Patty_Boop", "Hans2412",
             "JonasJAL", "FelipeCalderon", "DrSJaishankar", "Mzavalagc", "MEAIndia", 
             "SecBlinken", "StateDeptSpox", "qtf", "tatclouthier", "Cuauhtemoc_1521", 
             "benitoysolange", "marianagc", "AlfredoJalife2", "Democracia_mx",
             "Sergio Negrete Cárdenas","econokafka","E_Q_", "JLANoticias")

